services:
  nginx:
    image: nginx:alpine
    depends_on:
      - api
    ports:
      - "8080:80"         # まずは衝突しづらい 8080 を推奨。問題なければ 80:80 に戻してOK
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/usr/share/nginx/html:ro   # ← ここを追加（任意）

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: node-docker-app-dev
    # Nginx経由だけにするなら下の ports は消してOK。直アクセスしたいなら残す
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 3s
      retries: 3

  db:
    image: postgres:16-alpine
    container_name: node-docker-app-db
    env_file:
      - .env
    ports:
      - "5432:5432"       # psql で外から繋がないなら外してOK
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h 127.0.0.1"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  pgdata:
